/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SampleApp {
  id: string;
  title: string;
  description: string;
  icon: string;
  prompt: string;
  getCode: () => string;
}

export const SAMPLE_APPS: SampleApp[] = [
  {
    id: 'web-logs-explorer',
    title: 'Web Logs Explorer',
    description: 'Explore web server logs with response code filtering and byte transfer stats',
    icon: 'logsApp',
    prompt:
      'Build a web logs explorer for opensearch_dashboards_sample_data_logs with response code filtering, a table showing recent logs, and byte transfer statistics',
    getCode: () => WEB_LOGS_EXPLORER,
  },
  {
    id: 'flight-delays-dashboard',
    title: 'Flight Delays Dashboard',
    description: 'Flight delay analysis with carrier stats and delay distribution',
    icon: 'visLine',
    prompt:
      'Create a flight delays dashboard for opensearch_dashboards_sample_data_flights showing delay stats by carrier, average delay times, and cancellation rates',
    getCode: () => FLIGHT_DELAYS_DASHBOARD,
  },
  {
    id: 'ecommerce-overview',
    title: 'eCommerce Overview',
    description: 'Sales overview with revenue stats and top products',
    icon: 'search',
    prompt:
      'Build an ecommerce overview app for opensearch_dashboards_sample_data_ecommerce with total revenue, order count, top products, and sales by category',
    getCode: () => ECOMMERCE_OVERVIEW,
  },
];

/* eslint-disable */

var WEB_LOGS_EXPLORER = [
'var React = require("react");',
'var eui = require("@elastic/eui");',
'',
'exports.default = function WebLogsExplorer(props) {',
'  var api = props.api;',
'  var useState = React.useState;',
'  var useEffect = React.useEffect;',
'  var useCallback = React.useCallback;',
'',
'  var _logs = useState([]);',
'  var logs = _logs[0]; var setLogs = _logs[1];',
'  var _loading = useState(true);',
'  var loading = _loading[0]; var setLoading = _loading[1];',
'  var _filter = useState("all");',
'  var filter = _filter[0]; var setFilter = _filter[1];',
'  var _stats = useState({ total: 0, bytes: 0, errors: 0 });',
'  var stats = _stats[0]; var setStats = _stats[1];',
'',
'  var fetchLogs = useCallback(function() {',
'    setLoading(true);',
'    var query = "source=opensearch_dashboards_sample_data_logs | sort timestamp desc | head 50";',
'    api.search({ query: query, language: "PPL" })',
'      .then(function(res) {',
'        var hits = res && res.jsonData ? res.jsonData : [];',
'        setLogs(hits);',
'        var totalBytes = hits.reduce(function(s, h) { return s + (h.bytes || 0); }, 0);',
'        var errorCount = hits.filter(function(h) { var r = String(h.response || ""); return r.charAt(0) === "4" || r.charAt(0) === "5"; }).length;',
'        setStats({ total: hits.length, bytes: totalBytes, errors: errorCount });',
'        setLoading(false);',
'      })',
'      .catch(function() { setLogs([]); setLoading(false); });',
'  }, [api]);',
'',
'  useEffect(function() { fetchLogs(); }, [fetchLogs]);',
'',
'  var getResponseColor = function(code) {',
'    var c = String(code).charAt(0);',
'    if (c === "2") return "secondary";',
'    if (c === "3") return "default";',
'    if (c === "4") return "warning";',
'    if (c === "5") return "danger";',
'    return "default";',
'  };',
'',
'  var filtered = filter === "all" ? logs : logs.filter(function(l) { return String(l.response || "").charAt(0) === filter; });',
'',
'  return React.createElement(eui.EuiPanel, { paddingSize: "l", style: { height: "100%", overflowY: "auto" } },',
'    React.createElement(eui.EuiFlexGroup, { alignItems: "center" },',
'      React.createElement(eui.EuiFlexItem, null,',
'        React.createElement(eui.EuiTitle, { size: "s" }, React.createElement("h2", null, "Web Logs Explorer"))',
'      ),',
'      React.createElement(eui.EuiFlexItem, { grow: false },',
'        React.createElement(eui.EuiButtonEmpty, { iconType: "refresh", onClick: fetchLogs, size: "s", isLoading: loading }, "Refresh")',
'      )',
'    ),',
'    React.createElement(eui.EuiText, { size: "xs", color: "subdued" }, "Index: opensearch_dashboards_sample_data_logs | Query: PPL"),',
'    React.createElement(eui.EuiSpacer, { size: "m" }),',
'    React.createElement(eui.EuiFlexGroup, { gutterSize: "l" },',
'      React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: String(stats.total), description: "Total Hits", titleColor: "primary" }))),',
'      React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: (stats.bytes / 1024).toFixed(1) + " KB", description: "Total Bytes", titleColor: "primary" }))),',
'      React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: String(stats.errors), description: "Errors (4xx/5xx)", titleColor: stats.errors > 0 ? "danger" : "secondary" })))',
'    ),',
'    React.createElement(eui.EuiSpacer, { size: "m" }),',
'    React.createElement(eui.EuiSelect, { options: [',
'      { value: "all", text: "All Responses" }, { value: "2", text: "2xx Success" },',
'      { value: "3", text: "3xx Redirect" }, { value: "4", text: "4xx Client Error" }, { value: "5", text: "5xx Server Error" }',
'    ], value: filter, onChange: function(e) { setFilter(e.target.value); }, prepend: "Filter" }),',
'    React.createElement(eui.EuiSpacer, { size: "m" }),',
'    loading',
'      ? React.createElement(eui.EuiLoadingSpinner, { size: "xl" })',
'      : React.createElement(eui.EuiBasicTable, {',
'          items: filtered,',
'          columns: [',
'            { field: "timestamp", name: "Time", width: "170px", render: function(t) { return React.createElement(eui.EuiText, { size: "xs" }, t ? new Date(t).toLocaleString() : "-"); } },',
'            { field: "request", name: "Request", truncateText: true },',
'            { field: "response", name: "Status", width: "80px", render: function(r) { return React.createElement(eui.EuiBadge, { color: getResponseColor(r) }, String(r || "-")); } },',
'            { field: "bytes", name: "Bytes", width: "80px", render: function(b) { return (b || 0).toLocaleString(); } },',
'            { field: "clientip", name: "Client IP", width: "120px" },',
'            { field: "geo.src", name: "Geo", width: "60px" }',
'          ],',
'          pagination: { initialPageSize: 10, pageSizeOptions: [10, 25, 50] }',
'        })',
'  );',
'};',
].join('\n');

var FLIGHT_DELAYS_DASHBOARD = [
'var React = require("react");',
'var eui = require("@elastic/eui");',
'',
'exports.default = function FlightDelays(props) {',
'  var api = props.api;',
'  var useState = React.useState;',
'  var useEffect = React.useEffect;',
'',
'  var _flights = useState([]);',
'  var flights = _flights[0]; var setFlights = _flights[1];',
'  var _loading = useState(true);',
'  var loading = _loading[0]; var setLoading = _loading[1];',
'  var _stats = useState({ total: 0, delayed: 0, cancelled: 0, avgDelay: 0 });',
'  var stats = _stats[0]; var setStats = _stats[1];',
'',
'  useEffect(function() {',
'    api.search({ query: "source=opensearch_dashboards_sample_data_flights | head 200", language: "PPL" })',
'      .then(function(res) {',
'        var hits = res && res.jsonData ? res.jsonData : [];',
'        setFlights(hits);',
'        var delayed = hits.filter(function(f) { return f.FlightDelay === true; });',
'        var cancelled = hits.filter(function(f) { return f.Cancelled === true; });',
'        var totalDelay = delayed.reduce(function(s, f) { return s + (f.FlightDelayMin || 0); }, 0);',
'        setStats({',
'          total: hits.length,',
'          delayed: delayed.length,',
'          cancelled: cancelled.length,',
'          avgDelay: delayed.length > 0 ? Math.round(totalDelay / delayed.length) : 0',
'        });',
'        setLoading(false);',
'      })',
'      .catch(function() { setLoading(false); });',
'  }, [api]);',
'',
'  var carrierMap = {};',
'  flights.forEach(function(f) {',
'    var c = f.Carrier || "Unknown";',
'    if (!carrierMap[c]) carrierMap[c] = { name: c, flights: 0, delayed: 0, cancelled: 0, totalDelay: 0 };',
'    carrierMap[c].flights += 1;',
'    if (f.FlightDelay) { carrierMap[c].delayed += 1; carrierMap[c].totalDelay += (f.FlightDelayMin || 0); }',
'    if (f.Cancelled) carrierMap[c].cancelled += 1;',
'  });',
'  var carriers = Object.keys(carrierMap).map(function(k) {',
'    var c = carrierMap[k];',
'    c.avgDelay = c.delayed > 0 ? Math.round(c.totalDelay / c.delayed) : 0;',
'    return c;',
'  }).sort(function(a, b) { return b.flights - a.flights; });',
'',
'  var delayRate = stats.total > 0 ? ((stats.delayed / stats.total) * 100).toFixed(1) : "0";',
'',
'  return React.createElement(eui.EuiPanel, { paddingSize: "l", style: { height: "100%", overflowY: "auto" } },',
'    React.createElement(eui.EuiTitle, { size: "s" }, React.createElement("h2", null, "Flight Delays Dashboard")),',
'    React.createElement(eui.EuiText, { size: "xs", color: "subdued" }, "Index: opensearch_dashboards_sample_data_flights | Query: PPL"),',
'    React.createElement(eui.EuiSpacer, { size: "m" }),',
'    loading ? React.createElement(eui.EuiLoadingSpinner, { size: "xl" }) : React.createElement(React.Fragment, null,',
'      React.createElement(eui.EuiFlexGroup, { gutterSize: "l" },',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: stats.total.toLocaleString(), description: "Total Flights", titleColor: "primary" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: delayRate + "%", description: "Delay Rate", titleColor: Number(delayRate) > 20 ? "danger" : "secondary" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: String(stats.cancelled), description: "Cancellations", titleColor: "danger" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: stats.avgDelay + " min", description: "Avg Delay", titleColor: "warning" })))',
'      ),',
'      React.createElement(eui.EuiSpacer, { size: "l" }),',
'      React.createElement(eui.EuiTitle, { size: "xs" }, React.createElement("h3", null, "By Carrier")),',
'      React.createElement(eui.EuiSpacer, { size: "s" }),',
'      React.createElement(eui.EuiBasicTable, {',
'        items: carriers,',
'        columns: [',
'          { field: "name", name: "Carrier" },',
'          { field: "flights", name: "Flights" },',
'          { field: "delayed", name: "Delayed", render: function(v) { return React.createElement(eui.EuiBadge, { color: "warning" }, String(v)); } },',
'          { field: "cancelled", name: "Cancelled", render: function(v) { return React.createElement(eui.EuiBadge, { color: "danger" }, String(v)); } },',
'          { field: "avgDelay", name: "Avg Delay", render: function(v) { return v + " min"; } },',
'          { name: "Delay %", render: function(item) {',
'            var rate = item.flights > 0 ? ((item.delayed / item.flights) * 100).toFixed(1) : "0";',
'            return React.createElement(eui.EuiFlexGroup, { alignItems: "center", gutterSize: "s" },',
'              React.createElement(eui.EuiFlexItem, { grow: false }, rate + "%"),',
'              React.createElement(eui.EuiFlexItem, null, React.createElement("div", { style: { width: Math.min(Number(rate), 100) + "%", maxWidth: "100px", height: "8px", background: Number(rate) > 20 ? "#BD271E" : "#006BB4", borderRadius: "4px" } }))',
'            );',
'          }}',
'        ]',
'      })',
'    )',
'  );',
'};',
].join('\n');

var ECOMMERCE_OVERVIEW = [
'var React = require("react");',
'var eui = require("@elastic/eui");',
'',
'exports.default = function EcommerceOverview(props) {',
'  var api = props.api;',
'  var useState = React.useState;',
'  var useEffect = React.useEffect;',
'',
'  var _orders = useState([]);',
'  var orders = _orders[0]; var setOrders = _orders[1];',
'  var _loading = useState(true);',
'  var loading = _loading[0]; var setLoading = _loading[1];',
'  var _tab = useState("orders");',
'  var tab = _tab[0]; var setTab = _tab[1];',
'',
'  useEffect(function() {',
'    api.search({ query: "source=opensearch_dashboards_sample_data_ecommerce | head 100", language: "PPL" })',
'      .then(function(res) {',
'        var hits = res && res.jsonData ? res.jsonData : [];',
'        setOrders(hits);',
'        setLoading(false);',
'      })',
'      .catch(function() { setLoading(false); });',
'  }, [api]);',
'',
'  var totalRevenue = orders.reduce(function(s, o) { return s + (o.taxful_total_price || 0); }, 0);',
'  var avgOrder = orders.length > 0 ? (totalRevenue / orders.length).toFixed(2) : "0";',
'  var uniqueCustomers = {};',
'  orders.forEach(function(o) { if (o.customer_full_name) uniqueCustomers[o.customer_full_name] = true; });',
'',
'  var categoryMap = {};',
'  orders.forEach(function(o) {',
'    var cats = o.category || [];',
'    cats.forEach(function(c) {',
'      if (!categoryMap[c]) categoryMap[c] = { name: c, orders: 0, revenue: 0 };',
'      categoryMap[c].orders += 1;',
'      categoryMap[c].revenue += (o.taxful_total_price || 0);',
'    });',
'  });',
'  var categories = Object.keys(categoryMap).map(function(k) { return categoryMap[k]; }).sort(function(a, b) { return b.revenue - a.revenue; });',
'',
'  return React.createElement(eui.EuiPanel, { paddingSize: "l", style: { height: "100%", overflowY: "auto" } },',
'    React.createElement(eui.EuiTitle, { size: "s" }, React.createElement("h2", null, "eCommerce Overview")),',
'    React.createElement(eui.EuiText, { size: "xs", color: "subdued" }, "Index: opensearch_dashboards_sample_data_ecommerce | Query: PPL"),',
'    React.createElement(eui.EuiSpacer, { size: "m" }),',
'    loading ? React.createElement(eui.EuiLoadingSpinner, { size: "xl" }) : React.createElement(React.Fragment, null,',
'      React.createElement(eui.EuiFlexGroup, { gutterSize: "l" },',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: "$" + totalRevenue.toFixed(0).replace(/\\B(?=(\\d{3})+(?!\\d))/g, ","), description: "Total Revenue", titleColor: "secondary" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: String(orders.length), description: "Total Orders", titleColor: "primary" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: "$" + avgOrder, description: "Avg Order Value", titleColor: "primary" }))),',
'        React.createElement(eui.EuiFlexItem, null, React.createElement(eui.EuiPanel, { paddingSize: "m", hasBorder: true }, React.createElement(eui.EuiStat, { title: String(Object.keys(uniqueCustomers).length), description: "Customers", titleColor: "primary" })))',
'      ),',
'      React.createElement(eui.EuiSpacer, { size: "l" }),',
'      React.createElement(eui.EuiTabs, null,',
'        React.createElement(eui.EuiTab, { isSelected: tab === "orders", onClick: function() { setTab("orders"); } }, "Recent Orders"),',
'        React.createElement(eui.EuiTab, { isSelected: tab === "categories", onClick: function() { setTab("categories"); } }, "By Category")',
'      ),',
'      React.createElement(eui.EuiSpacer, { size: "m" }),',
'      tab === "orders"',
'        ? React.createElement(eui.EuiBasicTable, {',
'            items: orders.slice(0, 20),',
'            columns: [',
'              { field: "order_date", name: "Date", width: "170px", render: function(d) { return React.createElement(eui.EuiText, { size: "xs" }, d ? new Date(d).toLocaleString() : "-"); } },',
'              { field: "customer_full_name", name: "Customer" },',
'              { field: "category", name: "Category", render: function(cats) { return (cats || []).map(function(c, i) { return React.createElement(eui.EuiBadge, { key: i, color: "hollow" }, c); }); } },',
'              { field: "taxful_total_price", name: "Total", render: function(p) { return "$" + (p || 0).toFixed(2); } },',
'              { field: "currency", name: "Currency", width: "80px" }',
'            ],',
'            pagination: { initialPageSize: 10, pageSizeOptions: [10, 20] }',
'          })',
'        : React.createElement(eui.EuiBasicTable, {',
'            items: categories,',
'            columns: [',
'              { field: "name", name: "Category" },',
'              { field: "orders", name: "Orders" },',
'              { field: "revenue", name: "Revenue", render: function(r) { return "$" + r.toFixed(0).replace(/\\B(?=(\\d{3})+(?!\\d))/g, ","); } },',
'              { name: "Share", render: function(item) {',
'                var pct = totalRevenue > 0 ? ((item.revenue / totalRevenue) * 100).toFixed(1) : "0";',
'                return React.createElement(eui.EuiFlexGroup, { alignItems: "center", gutterSize: "s" },',
'                  React.createElement(eui.EuiFlexItem, { grow: false }, pct + "%"),',
'                  React.createElement(eui.EuiFlexItem, null, React.createElement("div", { style: { width: pct + "%", maxWidth: "150px", height: "8px", background: "#006BB4", borderRadius: "4px" } }))',
'                );',
'              }}',
'            ]',
'          })',
'    )',
'  );',
'};',
].join('\n');
/* eslint-enable */
