/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import {
    apiGatewayIcon,
    applicationIcon,
    appMeshIcon,
    appRunnerIcon,
    appSyncIcon,
    autoScalingIcon,
    bedrockIcon,
    cloudFormationIcon,
    cloudFrontIcon,
    cloudTrailIcon,
    cloudWatchIcon,
    dynamodbIcon,
    ebsIcon,
    ec2Icon,
    ecsIcon,
    eksIcon,
    elasticacheIcon,
    elasticBeanstalkIcon,
    elasticLoadbalancingIcon,
    emrIcon,
    eventBridgeIcon,
    fargateIcon,
    glacierIcon,
    k8sIcon,
    kinesisIcon,
    lambdaIcon,
    loadBalancerIcon,
    macieIcon,
    prometheusIcon,
    rdsIcon,
    redShiftIcon,
    route53Icon,
    rumIcon,
    s3Icon,
    serviceIcon,
    serviceLensUnknownNodeIcon,
    snsIcon,
    sqsIcon,
    stepFunctionIcon,
    syntheticsIcon,
    vpcIcon,
} from '../resources/services';

export const ICONS: Record<string, string> = {
    'AWS::APIGateway': apiGatewayIcon,
    'AWS::APM::Service': serviceLensUnknownNodeIcon,
    'AWS::ApplicationSignals::Application': applicationIcon,
    'AWS::AppMesh': appMeshIcon,
    'AWS::AppMesh::Mesh': appMeshIcon,
    'AWS::AppRunner': appRunnerIcon,
    'AWS::AppRunner::Service': appRunnerIcon,
    'AWS::AppSync': appSyncIcon,
    'AWS::AppSync::GraphQLApi': appSyncIcon,
    'AWS::AutoScaling': autoScalingIcon,
    'AWS::AutoScaling::AutoScalingGroup': autoScalingIcon,
    'AWS::Bedrock': bedrockIcon,
    'AWS::Bedrock::Model': bedrockIcon,
    'AWS::CloudFormation': cloudFormationIcon,
    'AWS::CloudFormation::Stack': cloudFormationIcon,
    'AWS::CloudFront': cloudFrontIcon,
    'AWS::CloudFront::Distribution': cloudFrontIcon,
    'AWS::CloudTrail': cloudTrailIcon,
    'AWS::CloudTrail::Trail': cloudTrailIcon,
    'AWS::CloudWatch': cloudWatchIcon,
    'AWS::CloudWatch::Alarm': cloudWatchIcon,
    'AWS::CloudWatch::Service': cloudWatchIcon,
    'AWS::DynamoDB': dynamodbIcon,
    'AWS::DynamoDB::Table': dynamodbIcon,
    'AWS::EC2::Volume': ebsIcon,
    'AWS::EC2': ec2Icon,
    'AWS::EC2::Instance': ec2Icon,
    'AWS::ECS': ecsIcon,
    'AWS::ECS::Service': fargateIcon,
    'AWS::ECS::Cluster': ecsIcon,
    'AWS::EKS': eksIcon,
    'AWS::EKS::Cluster': eksIcon,
    'AWS::Endpoint': serviceLensUnknownNodeIcon,
    'AWS::ElastiCache': elasticacheIcon,
    'AWS::ElastiCache::CacheCluster': elasticacheIcon,
    'AWS::ElasticBeanstalk': elasticBeanstalkIcon,
    'AWS::ElasticBeanstalk::Application': elasticBeanstalkIcon,
    'AWS::ElasticLoadBalancing': elasticLoadbalancingIcon,
    'AWS::ElasticLoadBalancing::LoadBalancer': elasticLoadbalancingIcon,
    'AWS::ElasticLoadBalancingV2::LoadBalancer': elasticLoadbalancingIcon,
    'AWS::EMR': emrIcon,
    'AWS::EMR::Cluster': emrIcon,
    'AWS::Events': eventBridgeIcon,
    'AWS::Events::Rule': eventBridgeIcon,
    'AWS::Glacier': glacierIcon,
    'AWS::Glacier::Vault': glacierIcon,
    'AWS::Kinesis': kinesisIcon,
    'AWS::Kinesis::Stream': kinesisIcon,
    K8s: k8sIcon,
    'AWS::Kubernetes': k8sIcon,
    'AWS::Macie': macieIcon,
    'AWS::Macie::CustomDataIdentifier': macieIcon,
    'AWS::APS': prometheusIcon,
    'AWS::APS::Workspace': prometheusIcon,
    'AWS::RDS': rdsIcon,
    'AWS::RDS::DBInstance': rdsIcon,
    'AWS::Redshift': redShiftIcon,
    'AWS::Redshift::Cluster': redShiftIcon,
    'AWS::Route53': route53Icon,
    'AWS::Route53::HostedZone': route53Icon,
    'AWS::Route53::RecordSet': route53Icon,
    'AWS::Lambda': lambdaIcon,
    'AWS::LoadBalancer': loadBalancerIcon,
    'AWS::Resource': serviceIcon,
    'AWS::RUM::AppMonitor': rumIcon,
    'AWS::RUM::Monitor': rumIcon,
    'AWS::S3': s3Icon,
    'AWS::S3::Bucket': s3Icon,
    'AWS::SNS': snsIcon,
    'AWS::SNS::Topic': snsIcon,
    'AWS::SQS': sqsIcon,
    'AWS::SQS::Queue': sqsIcon,
    'AWS::Synthetics': syntheticsIcon,
    'AWS::Synthetics::Canary': syntheticsIcon,
    'AWS::StepFunctions': stepFunctionIcon,
    'AWS::StepFunctions::StateMachine': stepFunctionIcon,
    'AWS::EC2::VPC': vpcIcon,
    'AWS::TargetGroup': loadBalancerIcon,
    'Remote::Endpoint': serviceLensUnknownNodeIcon,
    Generic: serviceLensUnknownNodeIcon,
    Unknown: serviceLensUnknownNodeIcon,
};
